name: Create Release Branch

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags || git fetch --tags

      - name: Run Release Please to generate the release PR
        id: rp
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          target-branch: dev

      - name: Extract new version
        id: version
        run: |
          VERSION="${{ steps.rp.outputs.version }}"
          if [ -z "$VERSION" ]; then
            echo "Não consegui detectar a versão da PR gerada."
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare release branch name
        id: branch
        run: |
          BRANCH="release/${{ steps.version.outputs.version }}"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "Criando branch: $BRANCH"

      - name: Create proper release branch
        run: |
          RELEASE_PR_BRANCH=$(echo "${{ steps.rp.outputs.pr-branch }}" | tr -d '"')
          git checkout "$RELEASE_PR_BRANCH"
          git pull
          git checkout -b "${{ steps.branch.outputs.branch }}"
          git push origin "${{ steps.branch.outputs.branch }}"

      - name: Create clean PR (release/x.x.x -> main)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = process.env.VERSION || "${{ steps.version.outputs.version }}";
            const branch = "release/" + version;

            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: branch,
              base: "main",
              title: `Release ${version}`,
              body: `This PR promotes version **${version}** to main.`
            });
